routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/books', 'BookController');
Route::resource('/comments', 'CommentController', ['only' => [ 'index', 'store', 'destroy', 'create']]);
Route::get('/contacts', 'ContactController@index')->name('contacts');
Route::get('filters/{id}', 'FilterController@show')->name('category_filter');
Route::resource('/users', 'UserController');
Route::resource('/illustrations', 'IllustrationController');
Route::resource('/quotes', 'QuoteController');
Route::resource('/', 'QuoteController');

resources/views/contact.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="cage clearfix">
                <div class="one">
                    <h3>Apie projektą</h3>
                <p><strong>Misija :</strong></p>
                <ul>
                    <li>Lietuvos gyventojų informacinių, kultūrinių ir laisvalaikio poreikių tenkinimas, atsižvelgiant į visų bendruomenės grupių informacinius kultūrinius bei socialinius poreikius.</li>
                    <li>Dalyvavimas žinių visuomenės kūrimo procesuose.</li>
                    <li>Knygų aprašymų, skaitytojų nuomonių kaupimas, tvarkymas, saugojimas ir teikimas Lietuvos gyventojams, atsižvelgiant į kultūrinį bei socialinį vystymą.</li>
                    <li>Knygų aprašymų, nuomonių apie knygas paslaugos teikiamos remiantis lygia naudojimosi teise visiems, nepaisant amžiaus, rasės, lyties, tautybės, socialinės padėties, politinių ar religinių įsitikinimų.</li>
                </ul>
                <p><strong>Vizija :</strong></p>
                <ul>
                    <li>Įgyti ir tobulinti informacinius, socialinius ir kultūrinius poreikius;</li>
                    <li>Naudotis savo demokratinėmis teisėmis;</li>
                    <li>Kūrybiškai dalyvauti žinių visuomenės kūrime.</li>
                </ul>
                <p><strong>Mes esame :</strong></p>
                <p>Zilvinas Entertainment&#x000A9;</p>
                </div>
                <div class="two">
                    <img class="contacts-img" src="http://www.startupremarkable.com/wp-content/uploads/2015/02/a-book-a-week-image.jpg" alt="picture">
                </div>
            </div>                
        </div>    
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>
                <div class="panel-body">
                    Jūs sėkmingai prisijungėte!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.main')

	@section('turinys')
	<main>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="flexslider">
	  					<ul class="slides">
	    					<li>
	      						<img src="{{ asset('img/1.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/2.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/3.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/4.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/5.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/6.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/7.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/8.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/9.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/10.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/11.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/12.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/13.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/14.jpg')}}" alt="img" />
	    					</li>
	    					<li>
	      						<img src="{{ asset('img/15.jpg')}}" alt="img" />
	    					</li>
	    				</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="font-weight">
						<h2>Karščiausios knygų naujienos :</h2>
					</div>
			        @if(Auth::user())
			        @if(Auth::user()->role == 'admin')
			        	@component('components.create', ['route' => 'quotes.create', 'name' => 'Sukurti naujieną']);
            			@endcomponent
            		@endif
            		@endif
       				<ul>
						@foreach($quotes as $quote)
							<li>
								<div class="new-book clearfix margin-top quote-back">
									<div class="user-image">
										<img src="{{ asset('img/default-book.jpg')}}" alt="img">
									</div>
									<div class="data">
										<div class="user-info font-weight">
											<span>{{ $quote->author }}</span>
										</div>
									</div>
									<div class="book-info padding-seven">
										<p> <i class="fa fa-circle" aria-hidden="true"></i> {{ substr($quote->quote, 0, 450) }}
										<a href="{{ route('quotes.show', $quote->id) }}">
			                            ...Skaityti daugiau</p>
			                        	</a>
									</div>
								</div>
							</li>
						@endforeach
					</ul>
				</div>
			</div>
		</div>	
	</main>
	@endsection