routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/books', 'BookController');
Route::resource('/comments', 'CommentController', ['only' => [ 'index', 'store', 'destroy', 'create']]);
Route::get('/contacts', 'ContactController@index')->name('contacts');
Route::get('filters/{id}', 'FilterController@show')->name('category_filter');
Route::resource('/users', 'UserController');
Route::resource('/illustrations', 'IllustrationController');
Route::resource('/quotes', 'QuoteController');
Route::resource('/', 'QuoteController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    public function creator() {
    	return $this->hasOne(
    		'App\User',
    		'id',
    		'created_by');
    }
    public function category() {
    	return $this->hasOne(
    		'App\Category',
    		'id',
    		'category_id');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Category;
use App\Comment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BookController extends Controller
{
    public function __construct() {
        $this->middleware('auth')->except('index', 'show');
        $this->middleware('admin')->except('store', 'index', 'show', 'create');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::orderBy('created_at', 'desc')->get();
        // Book::all();
        $count = count($books);
        // dd($count);
        return view ('books.index', ['books' => $books], compact('count'));
    }

    private function count($id) {
        $count = Book::where('id', $id)->count();
        return $count;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view ('books.create', compact('categories'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'author' => 'required',
            'image_url' => 'required',
            'year' => 'required|integer',
            'pages' => 'required|integer',
            'description' => 'required|min:3',
            'category' => 'required',
        ]);

        $book = new Book;
        $book->title = $request->input('title');
        $book->author = $request->input('author');
        $book->image_url = $request->input('image_url');
        $book->year = $request->input('year');
        $book->pages = $request->input('pages');
        $book->description = $request->input('description');
        $book->category_id = $request->input('category');
        $book->created_by = Auth::user()->id;
        $book->save();
        $request->session()->flash('success', 'Naujas knygos aprašymas sėkmingai sukurtas!');
        return redirect()->route('books.index');
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book, Request $request)
    {
        $comments = Comment::where('book_id',$book->id)->get();
        return view('books.show ', ['book' => $book, 'comments' => $comments]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $book = Book::find($id);
        //dd($book);
        return view('books.edit', compact('book', 'categories'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'author' => 'required',
            'image_url' => 'required',
            'year' => 'required|integer',
            'pages' => 'required|integer',
            'description' => 'required|min:3',
            'category' => 'required',
        ]);

        $book = Book::find($id);
        $book->title = $request->input('title');
        $book->author = $request->input('author');
        $book->image_url = $request->input('image_url');
        $book->year = $request->input('year');
        $book->pages = $request->input('pages');
        $book->description = $request->input('description');
        $book->category_id = $request->input('category');
        $book->created_by = Auth::user()->id;
        $book->save();
        return redirect()->route('books.index');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();
            return redirect()->route('books.index');
    }
}

resources/views/books/create.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Sukurti naują knygos aprašymą</div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ url('books') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-4 control-label">Knygos pavadinimas</label>
                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" autofocus>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
                            <label for="author" class="col-md-4 control-label">Autorius</label>
                            <div class="col-md-6">
                                <input id="author" type="text" class="form-control" name="author" value="{{ old('author') }}" >
                                @if ($errors->has('author'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('author') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('image_url') ? ' has-error' : '' }}">
                            <label for="image_url" class="col-md-4 control-label">Knygos viršelio nuotraukos nuoroda</label>
                            <div class="col-md-6">
                                <input id="image_url" type="text" class="form-control" name="image_url" value="{{ old('image_url') }}" >
                                @if ($errors->has('image_url'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image_url') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('year') ? ' has-error' : '' }}">
                            <label for="year" class="col-md-4 control-label">Leidimo metai</label>
                            <div class="col-md-6">
                                <input id="year" type="text" class="form-control" name="year" value="{{ old('year') }}">
                                @if ($errors->has('year'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('year') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('pages') ? ' has-error' : '' }}">
                            <label for="pages" class="col-md-4 control-label">Puslapių skaičius</label>
                            <div class="col-md-6">
                                <input id="pages" type="text" class="form-control" name="pages" value="{{ old('pages') }}">
                                @if ($errors->has('pages'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('pages') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Aprašymas</label>
                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control resize" name="description"></textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
                            <label for="category" class="col-md-4 control-label">Kategorija</label>
                            <div class="col-md-6">
                                <select id="category" type="text" class="form-control" name="category" value="{{ old('category') }}">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{ $category->category }}</option>
                                @endforeach
                                </select>
                                @if ($errors->has('category'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                       

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                @component('books.components.create') @endcomponent
                            </div>
                        </div>
                        @component('components.back') @endcomponent
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Redaguoti knygos aprašymą</div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ url('books/'.$book->id) }}">
                        <input name="_method" type="hidden" value="PUT">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-4 control-label">Knygos pavadinimas</label>
                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control" name="title" value="{{ old('title', $book->title) }}">
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
                            <label for="author" class="col-md-4 control-label">Autorius</label>
                            <div class="col-md-6">
                                <input id="author" type="text" class="form-control" name="author" value="{{ old('author', $book->author) }}" autofocus>
                                @if ($errors->has('author'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('author') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('image_url') ? ' has-error' : '' }}">
                            <label for="image_url" class="col-md-4 control-label">Knygos viršelio nuotraukos nuoroda</label>
                            <div class="col-md-6">
                                <input id="image_url" type="text" class="form-control" name="image_url" value="{{ old('image_url', $book->image_url) }}" >
                                @if ($errors->has('image_url'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image_url') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('year') ? ' has-error' : '' }}">
                            <label for="year" class="col-md-4 control-label">Leidimo metai</label>
                            <div class="col-md-6">
                                <input id="year" type="text" class="form-control" name="year" value="{{ old('year', $book->year) }}">
                                @if ($errors->has('year'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('year') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('pages') ? ' has-error' : '' }}">
                            <label for="pages" class="col-md-4 control-label">Puslapių skaičius</label>
                            <div class="col-md-6">
                                <input id="pages" type="text" class="form-control" name="pages" value="{{ old('pages', $book->pages) }}">
                                @if ($errors->has('pages'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('pages') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Aprašymas</label>
                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control resize" name="description">{{ old('description', $book->description) }}
                                </textarea>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
                            <label for="category" class="col-md-4 control-label">Kategorija</label>
                            <div class="col-md-6">
                                <select id="category" type="text" class="form-control" name="category">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}"
                                                @if($book->category_id == $category->id)
                                                selected
                                                @endif
                                        >{{ $category->category }}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('category'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                @component('books.components.edit') @endcomponent
                            </div>
                        </div>
                        @component('components.back') @endcomponent
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    @if(Session::get('success'))
    <div class="row">
        <div class="alert alert-success">
            {{ Session::get('success') }}
        </div>
    </div>
    @endif
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="cage clearfix">
                <div class="one">
                    <h3>Perskaitytų knygų aprašymai</h3>
                    <p>Visi geriausių ir mylimiausių knygų aprašymai bei skaitytojų komentarai! Aprašykite savo perskaitytą knygą, įkelkite savo mintis, knygos viršelio nuotrauką ir diskutuokite, dalinkitės mintimis, įžvalgomis, nuomonėmis su bendraminčiais!</p>
                </div>
                <div class="two">
                    <img class="contacts-img" src="{{ asset('img/writer.jpg')}}" alt="img">
                </div>
            </div>                
        </div>    
    </div>
    <div class="row book-list-reset">
        <div class="col-md-12 col-sm-12">
            <h3>Iš viso : <span>{{ $count }}</span> knygų aprašymų(-ai) !</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            @component('components.create', ['route' => 'books.create', 'name' => 'Sukurti naują knygos aprašymą']);
            @endcomponent
        </div>
    </div>
    <div class="row book-list-reset">
        <ul class="list-group col-md-12 col-sm-12">
            @foreach($books as $book)
                <li class="list-group-item clearfix book-list">
                    <div class="col-md-1 col-sm-1">
                        <a href="{{ route('books.show', $book->id) }}">
                            <img class="img-responsive" src="{{$book->image_url}}">
                        </a>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <strong>{{$book->title}}</strong>
                        <p></p>
                        Autorius: {{$book->author}}
                        <p></p>
                        Išleista {{$book->year}} metais
                        <p></p>
                        Kategorija - {{$book->category->category}}
                    </div>
                    <div class="col-md-7 col-sm-7">
                        {{ substr($book->description, 0, 450) }}
                        <a href="{{ route('books.show', $book->id) }}">
                            ...Skaityti daugiau
                        </a>
                    </div>
                    <div class="col-md-2 col-sm-7">
                        Sukūrė: {{ $book->creator->nickname }}
                        @component('components.delete', ['book' => $book, 'route' => 'books.destroy', 'id' => $book->id, 'name' => 'Ištrinti knygą']);
                        @endcomponent
                        @component('components.edit', ['route' => 'books.edit', 'id' => $book->id, 'name' => 'Redaguoti']);
                        @endcomponent
                    </div>
                </li>
            @endforeach
        </ul>
    </div>
</div>
@endsection

resources/views/books/show.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    <div class="row">
        <div class="col-md-12 margin-top">
            @component('components.delete', ['book' => $book, 'route' => 'books.destroy', 'id' => $book->id, 'name' => 'Ištrinti knygą']);
            @endcomponent
            @component('components.edit', ['route' => 'books.edit', 'id' => $book->id, 'name' => 'Redaguoti']);
            @endcomponent
        </div>
    </div>
    <div class="row book-list-reset">    
        <ul class="list-group col-md-12 col-sm-12">
            <li class="list-group-item clearfix book-list">
                <div class="col-md-4 col-sm-1">
                    <img class="img-responsive" src="{{$book->image_url}}">
                    Sukūrė: {{ $book->creator->nickname }}
                </div>
                <div class="col-md-8">
                    <p class="pav">{{$book->title}}</p>
                    <p></p>
                    Autorius: {{$book->author}}
                    <p></p>
                    Išleista {{$book->year}} metais
                    <p></p>
                    {{$book->pages}} puslapių (-iai)
                    <p></p>
                    {{$book->description}}
                    <p></p>
                    Kategorija - {{$book->category->category}}
                </div>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Komentarai :</h3>
            <p></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 margin_bottom">
            <form method="POST" action="{{ route('comments.store') }}">
                {{ csrf_field() }}
                <input type="hidden" name="book_id" value="{{ $book->id }}" />
                <div class="col-md-2 col-sm-2 col-xs-2 comment-right">
                    <input class="comment-box" id="name" type="text" name="name" placeholder="Jūsų vardas" value="{{ old('name') }}">
                    @if ($errors->has('comments'))
                        <span class="help-block">
                            <strong>{{ $errors->first('comments') }}</strong>
                        </span>
                    @endif
                </div>
                <textarea id="comment" name="comment" rows="4" class="col-md-8 col-sm-8 col-xs-8 comment-box" placeholder='Komentaras'>{{ old('comment') }}</textarea>
                @component('books.components.comment') @endcomponent
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <ul>
                @foreach($comments as $comment)
                    <li class="comma clearfix">
                        <div class="comma-left">
                            <div class="comment-name">{{ $comment->name }}</div>
                            <img src="{{ asset('img/default-user.png')}}" alt="picture" class="comment-face">
                            <div class="comment-date">{{ $comment->created_at }}</div>
                        </div>
                        <div class="comment-comment comma-center"><i class="fa fa-commenting-o" aria-hidden="true"></i> {{ $comment->comment }}</div>
                        <div class="comma-right"></div>
                    </li>
                    @component('components.delete', ['book' => $book, 'route' => 'comments.destroy', 'id' => $comment->id, 'name' => 'Ištrinti netinkamą komentarą']);
                    @endcomponent
                @endforeach
            </ul>
        </div>
    </div>
</div>
@endsection