routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/books', 'BookController');
Route::resource('/comments', 'CommentController', ['only' => [ 'index', 'store', 'destroy', 'create']]);
Route::get('/contacts', 'ContactController@index')->name('contacts');
Route::get('filters/{id}', 'FilterController@show')->name('category_filter');
Route::resource('/users', 'UserController');
Route::resource('/illustrations', 'IllustrationController');
Route::resource('/quotes', 'QuoteController');
Route::resource('/', 'QuoteController');

app/Filter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Filter extends Model
{
    //
}

app/Http/Controllers/FilterController.php
<?php

namespace App\Http\Controllers;

use App\Filter;
use App\Book;
use Illuminate\Http\Request;

class FilterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Filter  $filter
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $books = Book::where('category_id', $id)->get();
        $count = count($books);
        return view('filters.show', compact('books', 'count'));
    }

    private function count($id) {
        $count = Book::where('id', $id)->count();
        return $count;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Filter  $filter
     * @return \Illuminate\Http\Response
     */
    public function edit(Filter $filter)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Filter  $filter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Filter $filter)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Filter  $filter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Filter $filter)
    {
        //
    }
}

resources/views/filters/show.blade.php
@extends('layouts.main')

@section('turinys')
<div class="container">
    @if(Session::get('success'))    
    <div class="row">
        <div class="alert alert-success">
            {{ Session::get('success') }}
        </div>
    </div>
    @endif
    @if( count($books) != 0 )
    <div class="row">
        <div class="col-md-12">
            <h3>{{ $books[0]->category->category }} <span>({{ $count }})</span> knygų aprašymų(-ai)</h3>
        </div>
    </div>
    <div class="row book-list-reset">
        <ul class="list-group col-md-12">
            @foreach($books as $book)
                <li class="list-group-item clearfix book-list">
                    <div class="col-md-1">
                        <a href="{{ route('books.show', $book->id) }}">
                            <img class="img-responsive" src="{{$book->image_url}}">
                        </a>
                    </div>
                    <div class="col-md-2">
                        <strong>{{$book->title}}</strong>
                        <p></p>
                        Autorius: {{$book->author}}
                        <p></p>
                        Išleista {{$book->year}} metais
                        <p></p>
                        Kategorija - {{$book->category->category}}
                    </div>
                    <div class="col-md-7">
                        {{ substr($book->description, 0, 450) }}
                        <a href="{{ route('books.show', $book->id) }}">
                            ...Skaityti daugiau
                        </a>
                    </div>
                    <div class="col-md-2">
                        Sukūrė: {{ $book->creator->nickname }}
                        @component('components.delete', ['book' => $book, 'route' => 'books.destroy', 'id' => $book->id, 'name' => 'Ištrinti knygą']);
                        @endcomponent
                        @component('components.edit', ['route' => 'books.edit', 'id' => $book->id, 'name' => 'Redaguoti']);
                        @endcomponent
                    </div>
                </li>
            @endforeach
        </ul>
    </div>
    @else
    <h3>Jūsų pasirinkta kategorija tuščia</h3>
    @endif
</div>
@endsection